version: "3.2"
services: 
  gitlab-busybox:
    image: busybox:latest
    container_name: gitlab-busybox
    volumes:
      - gitlab-conf:/var/gitlab/conf
      - gitlab-log:/var/gitlab/log
      - gitlab-data:/var/gitlab/data
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    restart: always
    volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    env_file:
      - common.env
    depends_on: 
      - gitlab-busybox
  gitlab-runner-busybox:
    image: busybox:latest
    container_name: gitlab-runner-busybox
    volumes:
      - gitlab-runner-conf:/var/gitlab-runner/conf
  gitlab-runner:
    build: 
      context: .
      dockerfile: Dockerfile-runner
    image: gitlab-runner-pip
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: always
    links:
      - gitlab
    volumes:
      - gitlab-runner-conf:/etc/gitlab-runner
    env_file:
      - common.env
    depends_on: 
      - gitlab-runner-busybox
      - gitlab
volumes: 
  gitlab-conf:
  gitlab-log:
  gitlab-data:
  gitlab-runner-conf: