version: "3.2"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab
    ports:
      - "80:80"
      - "22:22"
    restart: always
    volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    env_file:
      - common.env
  gitlab-runner:
    build: 
      context: ./runner
      dockerfile: Dockerfile
    image: gitlab-runner
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: always
    links:
      - gitlab
    volumes:
      - gitlab-runner-conf:/etc/gitlab-runner
    env_file:
      - common.env
    depends_on:
      - gitlab
volumes: 
  gitlab-conf:
  gitlab-log:
  gitlab-data:
  gitlab-runner-conf: